import { db } from "./db";
import { towns } from "@shared/schema";

const ctTowns = [
  {
    state: "CT",
    county: "Fairfield",
    townName: "Danbury",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: "https://danburyct-health.viewpointcloud.com",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 50, seasonal: 100 },
      notes: ["Must apply 30 days in advance"],
    },
    confidenceScore: 85,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Stamford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.stamfordct.gov/health",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 200, temporary: 75 },
      notes: ["Background check required for all operators"],
    },
    confidenceScore: 90,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Norwalk",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 60, seasonal: 125 },
      notes: ["Mail applications to Health Department"],
    },
    confidenceScore: 75,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Bridgeport",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.bridgeportct.gov",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 180, temporary: 65 },
      notes: ["Police clearance required"],
    },
    confidenceScore: 80,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "New Haven",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: "https://www.newhavenct.gov/health",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 250, temporary: 100, seasonal: 175 },
      notes: ["Yale event permits require additional approval"],
    },
    confidenceScore: 92,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Hartford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.hartfordct.gov",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 200, temporary: 80 },
      notes: ["Downtown permits limited availability"],
    },
    confidenceScore: 88,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "West Hartford",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 50, seasonal: 125 },
      notes: [],
    },
    confidenceScore: 70,
  },
  {
    state: "CT",
    county: "New London",
    townName: "New London",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 125, temporary: 40 },
      notes: [],
    },
    confidenceScore: 55,
  },
  {
    state: "CT",
    county: "Litchfield",
    townName: "Torrington",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: false,
      fees: { yearly: 100, temporary: 35 },
      notes: [],
    },
    confidenceScore: 45,
  },
  {
    state: "CT",
    county: "Middlesex",
    townName: "Middletown",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 50, seasonal: 100 },
      notes: ["Wesleyan campus events require university approval"],
    },
    confidenceScore: 65,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Greenwich",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.greenwichct.gov",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 300, temporary: 125 },
      notes: ["Higher insurance requirements", "Location approval required"],
    },
    confidenceScore: 85,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Milford",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 140, temporary: 45, seasonal: 95 },
      notes: ["Beach permits seasonal only"],
    },
    confidenceScore: 72,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Hamden",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 135, temporary: 50 },
      notes: [],
    },
    confidenceScore: 60,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Manchester",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 55 },
      notes: [],
    },
    confidenceScore: 58,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Bristol",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 120, temporary: 40 },
      notes: [],
    },
    confidenceScore: 50,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Westport",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.westportct.gov",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 275, temporary: 100 },
      notes: ["Limited locations approved for food trucks"],
    },
    confidenceScore: 82,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Fairfield",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 60, seasonal: 120 },
      notes: [],
    },
    confidenceScore: 68,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Wallingford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: false,
      fees: { yearly: 130, temporary: 45 },
      notes: [],
    },
    confidenceScore: 55,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Enfield",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 110, temporary: 35 },
      notes: [],
    },
    confidenceScore: 42,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Meriden",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 125, temporary: 40 },
      notes: [],
    },
    confidenceScore: 52,
  },
];

export async function seedTowns() {
  try {
    const existingTowns = await db.select().from(towns);
    if (existingTowns.length > 0) {
      console.log(`Towns already seeded (${existingTowns.length} towns found)`);
      return;
    }

    console.log("Seeding CT towns...");
    for (const town of ctTowns) {
      await db.insert(towns).values(town);
    }
    console.log(`Seeded ${ctTowns.length} CT towns`);
  } catch (error) {
    console.error("Error seeding towns:", error);
  }
}
