import { db } from "./db";
import { towns, configs, profiles, publicProfiles, reviews, foodTrucks } from "@shared/schema";
import { users } from "@shared/models/auth";
import { runFullCTSeed } from "./seed-ct-towns";
import bcrypt from "bcrypt";
import { eq } from "drizzle-orm";

// Seed the default user for email/password login
async function seedDefaultUser() {
  const email = "23luis.leite@gmail.com";
  const password = "Permittracker2025!";
  
  try {
    // Check if user already exists
    const [existingUser] = await db.select().from(users).where(eq(users.email, email));
    
    if (existingUser) {
      // Update password if user exists but doesn't have password
      if (!existingUser.passwordHash) {
        const passwordHash = await bcrypt.hash(password, 10);
        await db.update(users)
          .set({ passwordHash, authProvider: "email" })
          .where(eq(users.email, email));
        console.log(`Updated password for user: ${email}`);
      } else {
        console.log(`User ${email} already exists with password`);
      }
      return;
    }
    
    // Create new user
    const passwordHash = await bcrypt.hash(password, 10);
    await db.insert(users).values({
      email,
      passwordHash,
      firstName: "Luis",
      lastName: "Leite",
      authProvider: "email",
      role: "owner",
    });
    console.log(`Created default user: ${email}`);
  } catch (error) {
    console.error("Error seeding default user:", error);
  }
}

const ctTowns = [
  {
    state: "CT",
    county: "Fairfield",
    townName: "Bethel",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: "https://bethel-ct.gov/?SEC=B6C10D79-A9D5-41BA-AB9A-934BA60CAB2D",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: false,
      menuRequired: true,
      fees: { yearly: 175, temporary: 75, seasonal: 100 },
      notes: [
        "CFPM certificate required for Class 2, 3, and 4",
        "24-hour emergency contact required",
        "Submit to Bethel Health Department",
        "License not issued if taxes delinquent 1+ years"
      ],
    },
    confidenceScore: 90,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Danbury",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: "https://danburyct-health.viewpointcloud.com",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 50, seasonal: 100 },
      notes: ["Must apply 30 days in advance"],
    },
    confidenceScore: 85,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Stamford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.stamfordct.gov/health",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 200, temporary: 75 },
      notes: ["Background check required for all operators"],
    },
    confidenceScore: 90,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Norwalk",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 60, seasonal: 125 },
      notes: ["Mail applications to Health Department"],
    },
    confidenceScore: 75,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Bridgeport",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.bridgeportct.gov",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 180, temporary: 65 },
      notes: ["Police clearance required"],
    },
    confidenceScore: 80,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "New Haven",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: "https://www.newhavenct.gov/health",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 250, temporary: 100, seasonal: 175 },
      notes: ["Yale event permits require additional approval"],
    },
    confidenceScore: 92,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Hartford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.hartfordct.gov",
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 200, temporary: 80 },
      notes: ["Downtown permits limited availability"],
    },
    confidenceScore: 88,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "West Hartford",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 50, seasonal: 125 },
      notes: [],
    },
    confidenceScore: 70,
  },
  {
    state: "CT",
    county: "New London",
    townName: "New London",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 125, temporary: 40 },
      notes: [],
    },
    confidenceScore: 55,
  },
  {
    state: "CT",
    county: "Litchfield",
    townName: "Torrington",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: false,
      fees: { yearly: 100, temporary: 35 },
      notes: [],
    },
    confidenceScore: 45,
  },
  {
    state: "CT",
    county: "Middlesex",
    townName: "Middletown",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 50, seasonal: 100 },
      notes: ["Wesleyan campus events require university approval"],
    },
    confidenceScore: 65,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Greenwich",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.greenwichct.gov",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 300, temporary: 125 },
      notes: ["Higher insurance requirements", "Location approval required"],
    },
    confidenceScore: 85,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Milford",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 140, temporary: 45, seasonal: 95 },
      notes: ["Beach permits seasonal only"],
    },
    confidenceScore: 72,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Hamden",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 135, temporary: 50 },
      notes: [],
    },
    confidenceScore: 60,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Manchester",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 150, temporary: 55 },
      notes: [],
    },
    confidenceScore: 58,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Bristol",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 120, temporary: 40 },
      notes: [],
    },
    confidenceScore: 50,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Westport",
    permitTypes: ["yearly", "temporary"],
    portalUrl: "https://www.westportct.gov",
    formType: "online_portal" as const,
    requirementsJson: {
      coi: true,
      background: true,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: true,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 275, temporary: 100 },
      notes: ["Limited locations approved for food trucks"],
    },
    confidenceScore: 82,
  },
  {
    state: "CT",
    county: "Fairfield",
    townName: "Fairfield",
    permitTypes: ["yearly", "temporary", "seasonal"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 175, temporary: 60, seasonal: 120 },
      notes: [],
    },
    confidenceScore: 68,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Wallingford",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: false,
      fees: { yearly: 130, temporary: 45 },
      notes: [],
    },
    confidenceScore: 55,
  },
  {
    state: "CT",
    county: "Hartford",
    townName: "Enfield",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "mail_in" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: false,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 110, temporary: 35 },
      notes: [],
    },
    confidenceScore: 42,
  },
  {
    state: "CT",
    county: "New Haven",
    townName: "Meriden",
    permitTypes: ["yearly", "temporary"],
    portalUrl: null,
    formType: "pdf_download" as const,
    requirementsJson: {
      coi: true,
      background: false,
      healthInspection: true,
      fireInspection: true,
      vehicleInspection: false,
      commissaryLetter: true,
      menuRequired: true,
      fees: { yearly: 125, temporary: 40 },
      notes: [],
    },
    confidenceScore: 52,
  },
];

const defaultConfigs = [
  { key: "pro_price", value: "29.99", description: "PermitPilot Pro monthly subscription price in USD" },
  { key: "basic_price", value: "0", description: "Basic plan monthly price in USD" },
  { key: "max_vehicles", value: "5", description: "Maximum vehicles per user" },
  { key: "pioneer_threshold", value: "60", description: "Confidence score below which users earn Pioneer badge" },
  { key: "stripe_publishable_key", value: "", description: "Stripe publishable key placeholder" },
  { key: "stripe_price_id_monthly", value: "", description: "Stripe monthly price ID for PermitPilot Pro" },
  { key: "subscription_plan_name", value: "PermitPilot Pro", description: "Paid plan label shown in billing UI" },
];

export async function seedTowns() {
  try {
    const existingTowns = await db.select().from(towns);
    if (existingTowns.length > 0) {
      console.log(`Towns already seeded (${existingTowns.length} towns found)`);
    } else {
      console.log("Seeding CT towns...");
      for (const town of ctTowns) {
        await db.insert(towns).values(town);
      }
      console.log(`Seeded ${ctTowns.length} CT towns`);
    }

    // Seed or update default configs
    const existingConfigs = await db.select().from(configs);
    const existingConfigMap = new Map(existingConfigs.map((config) => [config.key, config]));
    console.log("Ensuring default configs...");
    for (const config of defaultConfigs) {
      const existing = existingConfigMap.get(config.key);
      if (!existing) {
        await db.insert(configs).values(config);
        continue;
      }

      const shouldForceUpdateValue = config.key === "pro_price";
      if (shouldForceUpdateValue || existing.description !== config.description || existing.value === "") {
        await db
          .update(configs)
          .set({
            value: shouldForceUpdateValue ? config.value : existing.value,
            description: config.description,
          })
          .where(eq(configs.key, config.key));
      }
    }

    // Seed directory listings for CT food trucks (upsert-safe)
    console.log("Seeding CT food truck directory listings...");

    const ctDirectoryTrucks = [
      {
        profileId: "dir-truck-01",
        userId: "dir-user-01",
        vehicleType: "truck" as const,
        vehicleName: "Zuppardi's Apizza",
        menuType: "Pizza",
      },
      {
        profileId: "dir-truck-02",
        userId: "dir-user-02",
        vehicleType: "truck" as const,
        vehicleName: "Ricky D's Rib Shack",
        menuType: "BBQ",
      },
      {
        profileId: "dir-truck-03",
        userId: "dir-user-03",
        vehicleType: "truck" as const,
        vehicleName: "Muy Guapo Tacos",
        menuType: "Mexican",
      },
      {
        profileId: "dir-truck-04",
        userId: "dir-user-04",
        vehicleType: "truck" as const,
        vehicleName: "Melt Mobile",
        menuType: "American",
      },
      {
        profileId: "dir-truck-05",
        userId: "dir-user-05",
        vehicleType: "truck" as const,
        vehicleName: "Hardcore Sweet Cupcakes",
        menuType: "Desserts",
      },
      {
        profileId: "dir-truck-06",
        userId: "dir-user-06",
        vehicleType: "truck" as const,
        vehicleName: "The Whey Station",
        menuType: "American",
      },
      {
        profileId: "dir-truck-07",
        userId: "dir-user-07",
        vehicleType: "truck" as const,
        vehicleName: "Taco Loco",
        menuType: "Mexican",
      },
      {
        profileId: "dir-truck-08",
        userId: "dir-user-08",
        vehicleType: "truck" as const,
        vehicleName: "Caseus Fromagerie",
        menuType: "American",
      },
      {
        profileId: "dir-truck-09",
        userId: "dir-user-09",
        vehicleType: "truck" as const,
        vehicleName: "Señor Sisig CT",
        menuType: "Fusion",
      },
      {
        profileId: "dir-truck-10",
        userId: "dir-user-10",
        vehicleType: "truck" as const,
        vehicleName: "Joey B's Food Truck",
        menuType: "American",
      },
      {
        profileId: "dir-truck-11",
        userId: "dir-user-11",
        vehicleType: "truck" as const,
        vehicleName: "Krust Pizza",
        menuType: "Pizza",
      },
      {
        profileId: "dir-truck-12",
        userId: "dir-user-12",
        vehicleType: "truck" as const,
        vehicleName: "Arethusa al tavolo Mobile",
        menuType: "Farm-to-Table",
      },
    ];

    for (const p of ctDirectoryTrucks) {
      await db.insert(profiles).values({
        id: p.profileId,
        userId: p.userId,
        vehicleType: p.vehicleType,
        vehicleName: p.vehicleName,
        menuType: p.menuType,
      }).onConflictDoNothing();
    }

    const ctPublicProfiles = [
      {
        id: "dir-public-01",
        profileId: "dir-truck-01",
        userId: "dir-user-01",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Zuppardi's Apizza",
        description: "Famous New Haven-style apizza since 1934. Wood-fired thin crust pizza from a legendary CT institution.",
        cuisineType: "Pizza",
        county: "New Haven",
        locationLat: "41.2733",
        locationLng: "-72.9476",
        locationAddress: "West Haven, CT",
        website: "https://www.zuppardisapizza.com",
      },
      {
        id: "dir-public-02",
        profileId: "dir-truck-02",
        userId: "dir-user-02",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Ricky D's Rib Shack",
        description: "Award-winning BBQ ribs, brisket, and pulled pork. A Connecticut BBQ institution.",
        cuisineType: "BBQ",
        county: "New Haven",
        locationLat: "41.3082",
        locationLng: "-72.9251",
        locationAddress: "New Haven, CT",
        website: "https://www.rickydsribshack.com",
      },
      {
        id: "dir-public-03",
        profileId: "dir-truck-03",
        userId: "dir-user-03",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Muy Guapo Tacos",
        description: "Authentic Mexican street food. Tacos, burritos, and quesadillas with homemade salsas.",
        cuisineType: "Mexican",
        county: "Fairfield",
        locationLat: "41.2049",
        locationLng: "-73.2060",
        locationAddress: "Bridgeport, CT",
        website: "https://www.muyguapotacos.com",
      },
      {
        id: "dir-public-04",
        profileId: "dir-truck-04",
        userId: "dir-user-04",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Melt Mobile",
        description: "Gourmet grilled cheese sandwiches and comfort food. Creative flavor combinations on artisan bread.",
        cuisineType: "American",
        county: "Hartford",
        locationLat: "41.7637",
        locationLng: "-72.6851",
        locationAddress: "Hartford, CT",
        website: "https://www.meltmobilect.com",
      },
      {
        id: "dir-public-05",
        profileId: "dir-truck-05",
        userId: "dir-user-05",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Hardcore Sweet Cupcakes",
        description: "Over-the-top cupcakes and desserts. Unique flavors and beautiful designs for events.",
        cuisineType: "Desserts",
        county: "Hartford",
        locationLat: "41.7480",
        locationLng: "-72.7457",
        locationAddress: "West Hartford, CT",
        website: "https://www.hardcoresweet.com",
      },
      {
        id: "dir-public-06",
        profileId: "dir-truck-06",
        userId: "dir-user-06",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "The Whey Station",
        description: "Artisanal grilled cheese truck. Locally sourced cheeses and creative sandwiches.",
        cuisineType: "American",
        county: "Middlesex",
        locationLat: "41.5565",
        locationLng: "-72.6557",
        locationAddress: "Middletown, CT",
        website: "https://www.thewheystation.com",
      },
      {
        id: "dir-public-07",
        profileId: "dir-truck-07",
        userId: "dir-user-07",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Taco Loco",
        description: "Authentic Mexican tacos, burritos, and Mexican street corn. Family recipes from Mexico City.",
        cuisineType: "Mexican",
        county: "New London",
        locationLat: "41.3557",
        locationLng: "-72.0995",
        locationAddress: "New London, CT",
        website: "https://www.tacolococt.com",
      },
      {
        id: "dir-public-08",
        profileId: "dir-truck-08",
        userId: "dir-user-08",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Caseus Fromagerie",
        description: "Cheese-focused food truck from the acclaimed New Haven restaurant. Mac & cheese, grilled cheese, cheese plates.",
        cuisineType: "American",
        county: "New Haven",
        locationLat: "41.3113",
        locationLng: "-72.9246",
        locationAddress: "New Haven, CT",
        website: "https://www.caseusnewhaven.com",
      },
      {
        id: "dir-public-09",
        profileId: "dir-truck-09",
        userId: "dir-user-09",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Señor Sisig CT",
        description: "Filipino-Mexican fusion. Burritos, tacos, and rice plates with a unique twist.",
        cuisineType: "Fusion",
        county: "Fairfield",
        locationLat: "41.1842",
        locationLng: "-73.1334",
        locationAddress: "Stratford, CT",
      },
      {
        id: "dir-public-10",
        profileId: "dir-truck-10",
        userId: "dir-user-10",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Joey B's Food Truck",
        description: "Classic American comfort food. Burgers, hot dogs, fries, and milkshakes done right.",
        cuisineType: "American",
        county: "Litchfield",
        locationLat: "41.5773",
        locationLng: "-73.4082",
        locationAddress: "New Milford, CT",
      },
      {
        id: "dir-public-11",
        profileId: "dir-truck-11",
        userId: "dir-user-11",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Krust Pizza",
        description: "Wood-fired Neapolitan pizza from a custom-built mobile oven. Fresh ingredients, crispy crust.",
        cuisineType: "Pizza",
        county: "Fairfield",
        locationLat: "41.2230",
        locationLng: "-73.2138",
        locationAddress: "Fairfield, CT",
      },
      {
        id: "dir-public-12",
        profileId: "dir-truck-12",
        userId: "dir-user-12",
        isPublic: true,
        isVerified: false,
        source: "directory",
        businessName: "Arethusa al tavolo Mobile",
        description: "Farm-to-table food truck from the renowned Arethusa Farm. Seasonal menus with local dairy and produce.",
        cuisineType: "Farm-to-Table",
        county: "Litchfield",
        locationLat: "41.7449",
        locationLng: "-73.2130",
        locationAddress: "Bantam, CT",
        website: "https://www.arethusaaltavolo.com",
      },
    ];

    for (const pub of ctPublicProfiles) {
      await db.insert(publicProfiles).values(pub).onConflictDoNothing();
    }
    console.log(`Seeded ${ctPublicProfiles.length} CT directory food trucks`);

    // Seed food_trucks table (CT Food Truck Directory)
    console.log("Seeding food_trucks directory...");
    const chefosMenu = [
      { name: "Wings", description: "Order of wings with your choice of flavor and quantity.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/WZX66FIKCAJM222QDTPFR4OI.jpeg" },
      { name: "Empanadas", description: "Your choice of chicken, beef or cheese.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/RTYWUVIPJ343DPUOZVH3MHJN.jpeg" },
      { name: "Rice Bowl", description: "Your choice of rice, beans, protein, lettuce, pico & cheese. Additional toppings available.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/C75T3JFGPMCMJWEKNXAMF7T4.jpeg" },
      { name: "Quesadilla", description: "Toasted tortilla with cheese and your choice of protein. Add chips & salsa, onion rings or fries.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/OZFK66AG5PH6L2KQN246EGRK.jpeg" },
      { name: "Taco Meal", description: "3 flour shells with your choice of protein, shredded lettuce, pico, cheese, sour cream.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/23ECRTDMZ7UJNBWRSKTLBMMP.jpeg" },
      { name: "Hibachi Burrito", description: "Burrito with fried rice sautéed with your choice of protein, peppers, onions and eggs.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/6GAMFOXCKWB74NIK6MQQJWBB.jpeg" },
      { name: "Chimichanga", description: "Fried burrito filled with rice, beans, topped with melted cheese and enchilada sauce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/C5FOD2KAT7O2QGKW6PNBX2FV.jpeg" },
      { name: "Burrito", description: "Toasted tortilla with rice, beans, protein, pico, lettuce, mix cheese and your choice of sauce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/YM2GQRA3OZDLUUJOD2BTX2XR.jpeg" },
      { name: "Loaded Nachos", description: "Nachos with lettuce, pico, nacho cheese, beans, guacamole, shredded cheese, sour cream and protein.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/KNJNUKIK3OJRWAXH47UUCS76.jpeg" },
      { name: "Loaded Tostones", description: "Fried plantain with lettuce, pico, cheese, beans, guacamole, sour cream and your choice of protein.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/XGRTWSIKR4OROQYLRZX7ZK5G.jpeg" },
      { name: "Loaded Fries", description: "Fries with your choice of protein, nacho cheese, bacon and pico de gallo.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/NRETILXKHNC7A27TOLCEBRU6.jpeg" },
      { name: "Streatery Fried Rice", description: "Fried rice with eggs, fajitas, choice of protein, sour cream and lettuce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/4BTFYJ2MXYJC2RHB5M64EPE7.jpeg" },
      { name: "Chopped Cheese Crunch Wrap", description: "Ground beef, nacho cheese, mozzarella, sour cream, lettuce and pico de gallo in a toasted tortilla.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/GS7OBDYP6VF2K7LACGDKM37O.jpeg" },
      { name: "Taco Salad", description: "Lettuce, pico, shredded mix cheese, your choice of protein, beans, sauce, guacamole, served with tortilla chips.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/2ALM63TYITCQCPMYIYIISH3A.jpeg" },
      { name: "Esquites / Street Corn", description: "Street corn off the cob with lime mayo, cheese and chef sauce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/3RCZ5R4JSR7OE2SQQQMMMCFH.jpeg" },
      { name: "Churros", description: "Fried churros with optional dulce de leche dipping sauce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/VMGWIU46VLGAS5UDE3GKKN6M.jpeg" },
      { name: "Chicken Teriyaki Fried Dumplings", description: "8 chicken teriyaki fried dumplings with a side of teriyaki sauce.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/DI75QUOJTG33UMEN3FHMULC7.jpeg" },
      { name: "Fries", description: "Regular or cajun. Additional toppings and protein available.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/JVNJHUYGUXPYITY32HYBRSUC.jpeg" },
      { name: "Sides", description: "8oz container.", imageUrl: "https://141699077.cdn6.editmysite.com/uploads/1/4/1/6/141699077/OQ4QY3ML3RRAWJTGUGKWZSD7.jpeg" },
    ];

    const ctFoodTrucks = [
      {
        slug: "brazilian-bbq-boys",
        name: "Brazilian BBQ Boys",
        cuisine: "Brazilian BBQ",
        towns: ["Danbury", "Ridgefield", "Hartford", "West Hartford", "New Haven", "Fairfield County"],
        website: "https://www.brazilianbbqboys.com",
        email: "brazilianbbqboys@gmail.com",
        instagramHandle: "@brazilianbbqboys",
        description: "Authentic Brazilian churrasco on wheels. Picanha, linguiça, and slow-roasted meats with our signature sauces. Family-run, live-fire, serving CT.",
        status: "claimed",
        source: "founder",
        homeLat: "41.5582",
        homeLng: "-72.6507",
        offersPrivateCatering: true,
        cateringMinGuests: 50,
        cateringMaxGuests: 500,
        cateringPricePerPerson: "$18–$28/person",
        cateringDescription: "Full-service Brazilian churrasco for weddings, corporate events, and private parties. We bring the grill, the meat, and the experience.",
        cateringEventTypes: ["weddings", "corporate", "birthdays", "festivals", "graduations", "block parties"],
        cateringContactEmail: "brazilianbbqboys@gmail.com",
      },
      {
        slug: "taco-road-trip",
        name: "Taco Road Trip",
        cuisine: "Mexican",
        towns: ["Stamford", "Greenwich", "Norwalk"],
        description: "Street-style tacos made fresh to order. Carnitas, al pastor, and fish tacos with housemade salsa.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.7637",
        homeLng: "-72.6851",
        offersPrivateCatering: true,
        cateringMinGuests: 30,
        cateringMaxGuests: 200,
        cateringPricePerPerson: "$12–$18/person",
        cateringEventTypes: ["birthdays", "corporate", "block parties"],
      },
      {
        slug: "richs-wings-and-things",
        name: "Rich's Wings & Things",
        cuisine: "Wings / American",
        towns: ["Bridgeport", "New Haven", "Milford"],
        description: "Buffalo wings, tenders, and loaded fries. Sauces from mild to ghost pepper.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.3083",
        homeLng: "-72.9279",
      },
      {
        slug: "jesses-ice-cream-truck",
        name: "Jesse's Ice Cream Truck",
        cuisine: "Ice Cream / Desserts",
        towns: ["Glastonbury", "South Windsor", "Manchester"],
        description: "Soft serve, sundaes, and novelty ice cream. CT's favorite summer tradition.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.5582",
        homeLng: "-72.6507",
      },
      {
        slug: "nicky-zooks",
        name: "Nicky Zooks",
        cuisine: "American / Comfort Food",
        towns: ["Waterbury", "Naugatuck", "Ansonia"],
        description: "Loaded burgers, cheese steaks, and comfort food classics done the CT way.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.5582",
        homeLng: "-72.6507",
      },
      {
        slug: "fullmoon-taco-truck",
        name: "Fullmoon Taco Truck",
        cuisine: "Mexican",
        towns: ["New London", "Groton", "Norwich"],
        description: "Late-night tacos, burritos, and elotes. Open until the crowd goes home.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.7637",
        homeLng: "-72.6851",
      },
      {
        slug: "the-blind-rhino-food-truck",
        name: "The Blind Rhino Food Truck",
        cuisine: "Wings / BBQ",
        towns: ["Shelton", "Derby", "Ansonia"],
        website: "https://www.theblindrhino.com",
        description: "Extension of the Blind Rhino bar & grill. Craft wings, smash burgers, and street fries.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.5623",
        homeLng: "-72.6509",
        offersPrivateCatering: true,
        cateringMinGuests: 50,
        cateringMaxGuests: 300,
        cateringPricePerPerson: "$15–$22/person",
        cateringEventTypes: ["corporate", "birthdays", "block parties", "festivals"],
      },
      {
        slug: "chefos-eatery",
        name: "Chefo's Eatery",
        cuisine: "Puerto Rican-Mexican",
        towns: ["Hartford", "Bristol", "New Britain"],
        description: "Latin-inspired street food. Wings, empanadas, rice bowls, burritos, loaded fries, and more. Follow @chefostreatery on TikTok for our live schedule.",
        status: "unclaimed",
        source: "research",
        homeLat: "41.6617",
        homeLng: "-72.7795",
        email: "ChefOStreatery@Gmail.com",
        phone: "(860) 479-1317",
        instagramHandle: "ChefOStreatery",
        tiktokHandle: "chefostreatery",
        menuItems: chefosMenu,
      },
    ];
    for (const truck of ctFoodTrucks) {
      await db.insert(foodTrucks).values(truck as any).onConflictDoUpdate({
        target: foodTrucks.slug,
        set: {
          name: truck.name,
          cuisine: truck.cuisine,
          towns: truck.towns,
          website: (truck as any).website ?? null,
          email: (truck as any).email ?? null,
          instagramHandle: (truck as any).instagramHandle ?? null,
          description: truck.description,
          homeLat: (truck as any).homeLat ?? null,
          homeLng: (truck as any).homeLng ?? null,
          tiktokHandle: (truck as any).tiktokHandle ?? null,
          menuItems: (truck as any).menuItems ?? null,
          offersPrivateCatering: (truck as any).offersPrivateCatering ?? false,
          cateringMinGuests: (truck as any).cateringMinGuests ?? null,
          cateringMaxGuests: (truck as any).cateringMaxGuests ?? null,
          cateringPricePerPerson: (truck as any).cateringPricePerPerson ?? null,
          cateringDescription: (truck as any).cateringDescription ?? null,
          cateringEventTypes: (truck as any).cateringEventTypes ?? null,
          cateringContactEmail: (truck as any).cateringContactEmail ?? null,
        },
      });
    }
    console.log(`Seeded ${ctFoodTrucks.length} food trucks into directory`);

    await runFullCTSeed();
    
    // Seed default email/password user
    await seedDefaultUser();
  } catch (error) {
    console.error("Error seeding:", error);
  }
}
